app/controllers/bookings_controller.rb, app/controllers/reviews_controller.rb, app/controllers/toilets_controller.rb, app/controllers/users_controller.rb, config/routes.rb, test/controllers/bookings_controller_test.rb, test/controllers/reviews_controller_test.rb, test/controllers/toilets_controller_test.rb, test/controllers/users_controller_test.rb
we created bookings, users, toilets, reviews
=> created 4 controllers

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
I added the erb and css navbar code and edited the link titles
=> Added navbar erb and css and edited links names

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_search_form.scss, app/views/pages/home.html.erb, app/views/shared/_search_form.html.erb
made a search form container w/ css to mimic airbnb's style. need mike's banner
=> search form for home page

app/controllers/bookings_controller.rb, app/controllers/pages_controller.rb, app/controllers/reviews_controller.rb, app/controllers/toilets_controller.rb
Added basic functions with simple logic for further combined work and debugging
=> quick population of controllers for debugging purposes

app/assets/stylesheets/components/_booking_form.scss, app/assets/stylesheets/components/_index.scss, app/views/shared/_booking_form.html.erb, app/views/toilets/show.html.erb
created a booking form placeholder w/ css
=> prototype for booking form ready

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
I added a banner and footer to the page with a sample picture. I need help on moving the words up on the picture to take care of the search container thats going to go in.
=> Completed banner and footer

app/assets/stylesheets/components/_search_form.scss, app/assets/stylesheets/pages/_home.scss, app/views/devise/shared/_navbar.html.erb, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb, app/views/toilets/index.html.erb
- mounted search form into home page banner
- edited text color and size within banner
=> home page banner

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_toilet_cards.scss, app/views/shared/_navbar.html.erb, app/views/toilets/index.html.erb, app/views/toilets/show.html.erb, config/routes.rb, db/seeds.rb
Added links and looping to show and index
=> Toilets index

app/views/shared/_navbar.html.erb, config/routes.rb
Updated log in / log out buttons on navbar
=> Fixed logout

config/routes.rb
poopspace now officially the management dashboard
=> modified routes

app/assets/stylesheets/components/_booking_form.scss, app/controllers/toilets_controller.rb, app/views/devise/registrations/new.html.erb, app/views/shared/_booking_form.html.erb
- signup form: added first and last name input fields
- booking form: added input fields for check in and check out time. but needs modifications for interval pricing. also needs average rating displayed on page but our review model is not ready yet.
- toilets controller: refactored code. added a method that calculates average rating and sets it to @average_rating in #show. however, review model is not ready yet
=> Added input fields to signup and booking forms

app/assets/stylesheets/components/_booking.scss, app/assets/stylesheets/components/_index.scss, app/controllers/bookings_controller.rb, app/views/bookings/show.html.erb
-created a booking card for booking view
=> Booking card

app/assets/stylesheets/components/_booking.scss, app/assets/stylesheets/components/_booking_card_sm.scss, app/assets/stylesheets/components/_index.scss, app/views/poopspace/users/show.html.erb, app/views/shared/_booking_card_sm.html.erb
- made a small booking card to display on user account page
- created a container to arrange small booking cards in user account page
- check-in and check-out time currently unavailable due to formatting
=> Small booking card

app/views/bookings/show.html.erb
fixed control flow for bookings
=> fixed control flow

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_bookings_show.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/bookings_controller.rb, app/views/bookings/_show_current.html.erb, app/views/bookings/_show_other.html.erb
added a who's coming card for the host in bookings view
=> Booking view

app/models/toilet.rb
toilet name max character = 20
=> validation added

app/assets/stylesheets/components/_create_form.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_toilet_form.html.erb, app/views/toilets/_show_guest.html.erb, app/views/toilets/_show_host.html.erb, app/views/toilets/show.html.erb
=> Conflict 3

app/assets/stylesheets/pages/_poopspace.scss, app/assets/stylesheets/pages/_users_show.scss, app/views/poopspace/users/_show_host.html.erb
- added a modal window for listing toilets to save some poopspace
- added a profile card for listing info and editing profile
=> Modal list toilet

app/views/devise/sessions/new.html.erb
created some organization in the login page
=> touched up the login

app/controllers/bookings_controller.rb
The delete function started to work once tony changed the model.  I went ahead and changed the redirect to go back to the main poopspace page
=> Delete function was working just changed the redirect

app/assets/stylesheets/pages/_bookings_show.scss, app/views/toilets/_show_host.html.erb, app/views/toilets/edit.html.erb, config/routes.rb
made it look like really goooood
=> edit the shit out of this shit
